[project]
name = "icediscovery-greeter-server"
version = "0.1.0"
description = "IceDiscovery greeter demo server application"
requires-python = ">=3.12"
dependencies = ["zeroc-ice"]

[dependency-groups]
lint = [
    "pyright>=1.1.407",
    "ruff>=0.14.5",
]
