[project]
name = "client"
version = "0.1.0"
description = "Ice Greeter client"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["zeroc-ice"]


[tool.uv]
# Allow pre-releases globally (so the nightly zeroc-ice can be selected)
prerelease = "allow"

# Configure the ZeroC nightly index as an additional index,
# searched *before* the default PyPI index.
[[tool.uv.index]]
name = "zeroc-nightly"
url = "https://download.zeroc.com/nexus/repository/pypi-nightly/simple/"