[project]
name = "ice-config-server"
version = "0.1.0"
description = "Ice config demo server application"
requires-python = ">=3.12"
dependencies = ["zeroc-ice"]

[dependency-groups]
lint = [
    "pyright>=1.1.407",
    "ruff>=0.14.5",
]
