[project]
name = "ice-callback-server"
version = "0.1.0"
description = "Ice callback demo server application"
requires-python = ">=3.12"
dependencies = ["zeroc-ice", "common"]

[dependency-groups]
lint = [
    "pyright>=1.1.407",
    "ruff>=0.14.5",
]
